# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='new',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1050),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='display',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='display',
            field=models.CharField(max_length=150),
        ),
    ]
