# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostM', '0003_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='userTypeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostM.UserType'),
        ),
    ]
