# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admins_regin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='userinfos',
            field=models.CharField(default='user', max_length=500),
        ),
    ]
