# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admins_userinfos'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='loginsIP',
            field=models.GenericIPAddressField(default='0.0.0.0', null=True),
        ),
    ]
