# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161205_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='phonenum',
            field=models.PositiveIntegerField(),
        ),
    ]
